version: "2"
services:
  nginx:
    image: nginx:1.21.0
    expose:
      - 80
    volumes:
      - ./nginx_app.conf:/etc/nginx/conf.d/default.conf
      - ./srv:/usr/share/nginx/html/srv
      - ./logs:/var/log/nginx
    environment:
      VIRTUAL_HOST: domains.go.here
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: domains.go.here
      LETSENCRYPT_EMAIL: email@goes.here
    logging:
      options:
        max-size: 50m
  ws-multiplexor:
    container_name: ws-multiplexor
    build: .
    volumes:
      - ./app:/app
    environment:
      NODE_ENV: production
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx-proxy
